# Bandit security scanner configuration
# https://bandit.readthedocs.io/en/latest/config.html

# Exclude paths
exclude_dirs:
  - tests/
  - .approval_tests_temp/

# Skip certain tests
skips:
  - B101  # assert_used - common in tests

# Severity levels to report
severity:
  - HIGH
  - MEDIUM
  - LOW
  - UNDEFINED

# Confidence levels to report
confidence:
  - HIGH
  - MEDIUM
  - LOW
  - UNDEFINED